#!/bin/sh

# directory of this script
BASEDIR=$(dirname $0)

# absolute path to this script
DIR=$(cd "$BASEDIR" && pwd | sed 's/ /\\\\ /g')

clean() {
   TEMPLATES=$(echo ${DIR}/${EXAMPLEDIR}/*hpp.in)
   TEMPLATES=${TEMPLATES#"${DIR}/${EXAMPLEDIR}/"}
   TEMPLATES=${TEMPLATES%.hpp.in}

   for FILE in ${DIR}/../../templates/observables/${TEMPLATES}.*.in; do
      if [ -f ${FILE} ]; then
         rm ${FILE}
      fi
   done

   for FILE in ${DIR}/../../models/SM/observables/${TEMPLATES}.*; do
      if [ -f ${FILE} ]; then
         rm ${FILE}
      fi
   done

   META=$(echo ${DIR}/${EXAMPLEDIR}/*/)
   META=${META#"${DIR}/${EXAMPLEDIR}/"}
   META=${META%/}

   FSMETA=${DIR}/../../meta/Observables/${META}
   if [ -d ${FSMETA} ]; then
      rm -rf ${FSMETA}
   fi
}

copythings(){
   cp ${DIR}/${EXAMPLEDIR}/${TEMPLATES}* ${DIR}/../../templates/observables
   mkdir ${FSMETA}
   cp ${DIR}/${EXAMPLEDIR}/${META}/*.m ${FSMETA}
}

leptonSelfEnergy() {
   cd ${DIR}/../../meta/NPointFunctions
   _anchor='Begin@"`Private`";'
   _topo='AllTopologies\[{1, 1}\] = {'
   _sun='   sunset  -> {1,0,0,1,0,2,0},'
   if [ -z "$(grep "${_topo}" Topologies.m)" ]; then
      sed -i "s/${_anchor}/${_anchor}\n\
\n\
${_topo}\n\
   tadpole -> {1,0,1,0,0,1,1},\n\
${_sun}\n\
   fermi   -> {tadpole, sunset}\n\
};/g" Topologies.m
   elif [ -z "$(grep "${_sun}" Topologies.m)" ]; then
      sed -i "s/${_topo}/${_topo}\n${_sun}/g" Topologies.m
   fi
}

cleanall() {
   for _dir in ${DIR}/*; do
      if [ -d ${_dir} ]; then
         EXAMPLEDIR=$(echo ${_dir#"${DIR}/"})
         clean
      fi
   done
}

# MAIN begin
FSMODELDIR=${DIR}/../../models/SM/FlexibleSUSY.m
cleanall
case $1
in
   example-1) EXAMPLEDIR=constant-observable
              clean
              copythings
              echo 'ExtraSLHAOutputBlocks = {{FlexibleSUSYLowEnergy,{{1, FlexibleSUSYObservable`ExampleConstantObservable[1]},{2, FlexibleSUSYObservable`ExampleConstantObservable[2]}}}};' >> ${FSMODELDIR}
              ;;
   example-2) EXAMPLEDIR=fermion-mass-observable
              clean
              copythings
              echo 'ExtraSLHAOutputBlocks = {{FlexibleSUSYLowEnergy,{{1, FlexibleSUSYObservable`ExampleFermionMass[Fe@2]},{2, FlexibleSUSYObservable`ExampleFermionMass[Fd@2]}}},{ExampleLeptonMass,{{1, FlexibleSUSYObservable`ExampleFermionMass[Fe@2]},{2, FlexibleSUSYObservable`ExampleFermionMass[Fd@2]}}}};' >> ${FSMODELDIR}
              ;;
   example-3) EXAMPLEDIR=lepton-se
              clean
              copythings
              leptonSelfEnergy
              echo 'ExtraSLHAOutputBlocks = {{FWCOEF,{{1, FlexibleSUSYObservable`ExampleLeptonSE[Fe@1, {Sunsets}]}}}};' >> ${FSMODELDIR}
              ;;
   example-4) EXAMPLEDIR=post-processing
              clean
              copythings
              ;;
   example-5) EXAMPLEDIR=btosmumu
              clean
              copythings
              ;;
   clean-all) cleanall
              ;;
   *) exit 0;
esac
# MAIN end
