language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - libgsl0-dev
  homebrew:
    packages:
      - gsl
    update: true
install:
  - pip3 install --user conan
  - conan remote add conan-hep https://api.bintray.com/conan/expander/conan-hep
  - conan install . --build=missing
script:
  - ./configure --with-models= --with-optional-modules=test --with-addons=GM2Calc --disable-meta
  - make
  - make all-test
