language: cpp
os:
  - linux
  - osx
jobs:
  exclude:
  - compilex: gcc
    os: osx
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - libgsl0-dev
      - libsqlite3-dev
  homebrew:
    packages:
      - gfortran
      - gsl
      - sqlite
    update: true
install:
  - export PATH=$(python -c 'import site; print(site.USER_BASE + "/bin")'):$PATH
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink gcc; fi
  - pip install --user conan
  - conan remote add conan-hep https://api.bintray.com/conan/expander/conan-hep --force
  - conan install . --build=missing
script:
  - >
    ./configure
    --with-cxxflags="-std=c++14 -fPIC"
    --with-optional-modules=test
    --with-addons=GM2Calc
    --with-loop-libraries=collier,looptools
    --disable-meta
  - make showbuild
  - make -j2 VERBOSE=1
  - make test/test_looplibrary_collier.x VERBOSE=1
  - ./test/test_looplibrary_collier.x
  - make test/test_looplibrary_softsusy.x VERBOSE=1
  - ./test/test_looplibrary_softsusy.x
  - make -j2 all-test VERBOSE=1
