#!/bin/bash
exists_in_path () {
  if [ $# -ne 1 ]; then
    echo "Error: exists_in_path: Exactly one argument required"
    return 1
  fi

  command -v $1 >/dev/null 2>&1 || { echo "Error: \"$1\" not found!"; return 1; }
  return 0
}

[[ -d "$HOME/.local" ]] || { echo "Error: \"$HOME/.local\" doesn't exists!"; exit 1; }

echo -n "Checking the presence of required executables ... "
declare -a required_executables
required_executables=("wget" "tar" "rm" "cmake" "make" "sed")
for EXE in ${required_executables[*]}
do
  exists_in_path $EXE || exit 1
done
echo "done"

# default COLLIER version
collier_version="1.2.4"

install_path="$HOME/.local"
collier_dir="$install_path/COLLIER-$collier_version"

collier_tar="collier-$collier_version.tar.gz"
collier_download_url="https://collier.hepforge.org/downloads/$collier_tar"

cd $install_path
echo "Downloading $collier_tar to $install_path ... "
wget $collier_download_url || { echo "Error: failed!"; exit 1; }
echo "done"

echo -n "Extracting $collier_tar to $collier_dir ... "
tar -xf $collier_tar || { echo "Error: failed!"; exit 1; }
echo "done"

echo -n "Removing $collier_tar ... "
rm $collier_tar || { echo "Error: failed!"; exit 1; }
echo "done"

cd $collier_dir/build
echo -n "Generation of COLLIER library started ... "
cmake -Dstatic=ON ..
make_setup="$collier_dir/build/CMakeFiles/collier.dir/flags.make"
sed -i "s#Fortran_FLAGS = #Fortran_FLAGS = -fPIC #g" $make_setup
make
echo "done"
