ParameterDefinitions = {

{aEWinv, {Description-> "inverse weak coupling constant at mZ"}},
{AlphaS, {Description-> "Alpha Strong"}},
{e,      {Description-> "electric charge"}},
{g1,     {Description-> "Hypercharge-Coupling"}},
{g2,     {Description-> "Left-Coupling"}},
{g3,     {Description-> "Strong-Coupling"}},
{Gf,     {Description-> "Fermi's constant"}},
{mu2,    {Description-> "SM Mu Parameter"}},
{Ud,     {Description-> "Right-Down-Mixing-Matrix"}},
{Ue,     {Description-> "Right-Lepton-Mixing-Matrix"}},
{Uu,     {Description-> "Right-Up-Mixing-Matrix"}},
{Vd,     {Description-> "Left-Down-Mixing-Matrix"}},
{Ve,     {Description-> "Left-Lepton-Mixing-Matrix"}},
{Vu,     {Description-> "Left-Up-Mixing-Matrix"}},
{ZZ,     {Description-> "Photon-Z Mixing Matrix"}},
{ThetaW, {Description -> "Weinberg-Angle",
          DependenceNum -> ArcSin[Sqrt[1 - Mass[VWp]^2/Mass[VZ]^2]]  }},
{ZW,     {Description-> "W Mixing Matrix",
          Dependence-> 1/Sqrt[2] {{1, 1},
                                  {I,-I}}}},
{v,      {Description-> "EW-VEV",
          DependenceNum-> Sqrt[4*Mass[VWp]^2/(g2^2)],
          DependenceSPheno-> None}},
{\[Lambda], {Description-> "SM Higgs Selfcouplings",
             DependenceNum-> Mass[hh]^2/v^2}},
{Yd,     {Description-> "Down-Yukawa-Coupling",
          DependenceNum-> Sqrt[2]/v * DiagonalMatrix[Mass[Fd, #]&/@ Range@3]}},
{Yu,     {Description-> "Up-Yukawa-Coupling",
          DependenceNum-> Sqrt[2]/v * DiagonalMatrix[Mass[Fu, #]&/@ Range@3]}},
{Ye,     {Description-> "Lepton-Yukawa-Coupling",
          DependenceNum-> Sqrt[2]/v * DiagonalMatrix[Mass[Fe, #]&/@ Range@3]}},

(* BSM Parameters *)

{MS12,   {Real-> True,
          LesHouches-> {SCALARLEPTOQUARKS, 1},
          LaTeX-> "{M}_{S_1}^2",
          OutputName-> MS12}},
{gHS1,   {Real-> True,
          LesHouches-> {SCALARLEPTOQUARKS, 2},
          LaTeX-> "g_{HS_1}",
          OutputName-> gHS1}},
{lamS1,  {Real-> True,
          LesHouches-> {SCALARLEPTOQUARKS, 3},
          LaTeX-> "\\lambda_{S_1}",
          OutputName-> lamS1}},
{lamQL,  {Real-> False,
          LesHouches-> LAML,
          LaTeX-> "\\lambda_{QL}",
          OutputName-> lamQL}},
{lamql,  {Real-> False,
          LesHouches-> LAMR,
          LaTeX-> "\\lambda_{ql}",
          OutputName-> lamql}}
};
