(* ::Package:: *)

(* ::Input:: *)
(*(*SSF Diagram*)*)
(**)
(*SSFA2L[mi_,mj_,mF_,mS_,SFinleft_,SFoutleft_,SFinright_,SFoutright_]:=Module[{r},*)
(*r=Power[mF/mS,2];*)
(*(*eq.16 of hep-ph/9510309 (possibly with different sign) *)*)
(* Return[-SFoutleft[]*SFinright[]*OneLoopFunctionB[r]/12.-SFoutleft[]*SFinleft[]*mF/mj*OneLoopFunctionC[r]/3.-mi/mj*SFoutright[]*SFinleft[]*OneLoopFunctionB[r]/12.]*)
(*]*)
(*SSFA2LPV[mi_,mj_,mF_,mS_,SFinleft_,SFoutleft_,SFinright_,SFoutright_]:=Module[{r,mS2},*)
(*(*Massless emitter (in this case mS==0,mi==mj==mF) will fail *)*)
(*(*Massless mediator (in this case mF==0) case can be calculated*)*)
(*mS2=Power[mS,2];*)
(*If[mi==mj&&mi==mS&&mF==0.,*)
(*Return[-0.5*mS2*(SFinright[]*SFoutleft[]+SFinleft[]*SFoutright[])/Power[mi,2]],*)
(*Return[2 mS^2/mj (mF (PVC[0,0,0,mj^2,0,mi^2,mF,mS,mS]+PVC[0,0,1,mj^2,0,mi^2,mF,mS,mS]+PVC[0,1,0,mj^2,0,mi^2,mF,mS,mS]) SFinleft[] SFoutleft[]-mj (PVC[0,1,0,mj^2,0,mi^2,mF,mS,mS]+PVC[0,1,1,mj^2,0,mi^2,mF,mS,mS]+PVC[0,2,0,mj^2,0,mi^2,mF,mS,mS]) SFinright[] SFoutleft[]-mi (PVC[0,0,1,mj^2,0,mi^2,mF,mS,mS]+PVC[0,0,2,mj^2,0,mi^2,mF,mS,mS]+PVC[0,1,1,mj^2,0,mi^2,mF,mS,mS]) SFinleft[] SFoutright[])]*)
(*]*)
(*]*)
(**)
(*SSFA2R[mi_,mj_,mF_,mS_,SFinleft_,SFoutleft_,SFinright_,SFoutright_]:=Module[{r},*)
(*r=Power[mF/mS,2];*)
(*(*eq.15 of hep-ph/9510309 after replacement L\[TwoWayRule]R (possibly with different sign) *)*)
(* Return[-SFoutright[]*SFinleft[]*OneLoopFunctionB[r]/12.-SFoutright[]*SFinright[]*mF/mj*OneLoopFunctionC[r]/3.-mi/mj*SFoutleft[]*SFinright[]*OneLoopFunctionB[r]/12.]*)
(*]*)
(*SSFA2RPV[mi_,mj_,mF_,mS_,SFinleft_,SFoutleft_,SFinright_,SFoutright_]:=Module[{r,mS2},*)
(*(*Massless emitter (in this case mS==0,mi==mj==mF) will fail *)*)
(*(*Massless mediator (in this case mF==0) case can be calculated*)*)
(*mS2=Power[mS,2];*)
(*If[mi==mj&&mi==mS&&mF==0.,*)
(*Return[-0.5*mS2*(SFinright[]*SFoutleft[]+SFinleft[]*SFoutright[])/Power[mi,2]],*)
(*Return[mS^2/mj (-mi (PVC[0,0,1,mj^2,0,mi^2,mF,mS,mS]+PVC[0,0,2,mj^2,0,mi^2,mF,mS,mS]+PVC[0,1,1,mj^2,0,mi^2,mF,mS,mS]) SFinright[] SFoutleft[]-mj (PVC[0,1,0,mj^2,0,mi^2,mF,mS,mS]+PVC[0,1,1,mj^2,0,mi^2,mF,mS,mS]+PVC[0,2,0,mj^2,0,mi^2,mF,mS,mS]) SFinleft[] SFoutright[]+mF (PVC[0,0,0,mj^2,0,mi^2,mF,mS,mS]+PVC[0,0,1,mj^2,0,mi^2,mF,mS,mS]+PVC[0,1,0,mj^2,0,mi^2,mF,mS,mS]) SFinright[] SFoutright[])]*)
(*]*)
(*]*)
(**)
(*(*FFS Diagram*)*)
(**)
(*FFSA2L[mi_,mj_,mF_,mS_,SFinleft_,SFoutleft_,SFinright_,SFoutright_]:=Module[{r},*)
(*r=Power[mF/mS,2];*)
(*(*eq.19 of hep-ph/9510309 (possibly with different sign)*)*)
(*Return[-SFoutleft[]*SFinright[]*OneLoopFunctionE[r]/12.-SFoutleft[]*SFinleft[]*mF/mj*OneLoopFunctionF[r]*2./3.-mi/mj*SFoutright[]*SFinleft[]*OneLoopFunctionE[r]/12.]*)
(*]*)
(*FFSA2LPV[mi_,mj_,mF_,mS_,SFinleft_,SFoutleft_,SFinright_,SFoutright_]:=Module[{r,mS2},*)
(*(*Massless emitter (in this case mF\[Equal]0) will fail*)*)
(*(*Massless mediator (in this case mS\[Equal]0) case can be calculated*)*)
(*mS2=Power[mS,2];*)
(*If[mi==mj&&mi==mF&&mS==0,*)
(*Return[-0.5*mS2*(SFinright[]*SFoutleft[]+SFinleft[]*(4.*SFoutleft[]+SFoutright[]))/Power[mi,2]],*)
(*Return[2 mS2/mj (mF (-PVC[0,0,1,mj^2,0,mi^2,mS,mF,mF]-PVC[0,1,0,mj^2,0,mi^2,mS,mF,mF]) SFinleft[] SFoutleft[]-mj (PVC[0,1,0,mj^2,0,mi^2,mS,mF,mF]+PVC[0,1,1,mj^2,0,mi^2,mS,mF,mF]+PVC[0,2,0,mj^2,0,mi^2,mS,mF,mF]) SFinright[] SFoutleft[]-mi (PVC[0,0,1,mj^2,0,mi^2,mS,mF,mF]+PVC[0,0,2,mj^2,0,mi^2,mS,mF,mF]+PVC[0,1,1,mj^2,0,mi^2,mS,mF,mF]) SFinleft[] SFoutright[])];*)
(*]*)
(*]*)
(**)
(*FFSA2R[mi_,mj_,mF_,mS_,SFinleft_,SFoutleft_,SFinright_,SFoutright_]:=Module[{r},*)
(*r=Power[mF/mS,2];*)
(*(*eq.19 of hep-ph/9510309after replacement L\[TwoWayRule]R (possibly with different sign) *)*)
(*Return[-SFoutright[]*SFinleft[]*OneLoopFunctionE[r]/12.-SFoutright[]*SFinright[]*mF/mj*OneLoopFunctionF[r]*2./3.-mi/mj*SFoutleft[]*SFinright[]*OneLoopFunctionE[r]/12.]*)
(*]*)
(*FFSA2RPV[mi_,mj_,mF_,mS_,SFinleft_,SFoutleft_,SFinright_,SFoutright_]:=Module[{r,mS2},*)
(*(*Massless emitter (in this case mF\[Equal]0) will fail*)*)
(*(*Massless mediator (in this case mS\[Equal]0) case can be calculated*)*)
(*mS2=Power[mS,2];*)
(*If[mi==mj&&mi==mF&&mS==0,*)
(*Return[-0.5*mS2*(SFinleft[]*SFoutright[]+SFinright[]*(SFoutleft[]+4.*SFoutright[]))/Power[mi,2]],*)
(*Return[2 mS2/mj(-mi (PVC[0,0,1,mj^2,0,mi^2,mS,mF,mF]+PVC[0,0,2,mj^2,0,mi^2,mS,mF,mF]+PVC[0,1,1,mj^2,0,mi^2,mS,mF,mF]) SFinright[] SFoutleft[]-mj (PVC[0,1,0,mj^2,0,mi^2,mS,mF,mF]+PVC[0,1,1,mj^2,0,mi^2,mS,mF,mF]+PVC[0,2,0,mj^2,0,mi^2,mS,mF,mF]) SFinleft[] SFoutright[]+mF (-PVC[0,0,1,mj^2,0,mi^2,mS,mF,mF]-PVC[0,1,0,mj^2,0,mi^2,mS,mF,mF]) SFinright[] SFoutright[])]*)
(*]*)
(*]*)
(**)
(*(*VVF Diagram*)*)
(**)
(*VVFA2L[mi_,mj_,mF_,mV_,VFinleft_,VFoutleft_,VFinright_,VFoutright_]:=Module[{r},*)
(*r=Power[mF/mV,2];*)
(*Return[3.*mF/mj*VFinleft[]*VFoutright[]*OneLoopFunctionK[r]+mi/mj*VFinleft[]*VFoutleft[]*OneLoopFunctionJ[r]/6.+VFinright[]*VFoutright[]*OneLoopFunctionJ[r]/6.]*)
(*]*)
(*VVFA2LPV[mi_,mj_,mF_,mV_,VFinleft_,VFoutleft_,VFinright_,VFoutright_]:=Module[{r,mV2,\[ScriptD]},*)
(*(*Massless emitter (in this case mV\[Equal]0,mi\[Equal]mj\[Equal]mF) will fail*)*)
(*(*Massless mediator (in this case mF\[Equal]0) case can be calculated*)*)
(*mV2=Power[mV,2];*)
(*If[mi==mj&&mi==mV&&mF==0,*)
(*2.*mV2*(VFinleft[]*VFoutleft[]+VFinright[]*VFoutright[])/Power[mi,2],*)
(*Return[*)
(*2 mV2/mj (mi (-(-4+\[ScriptD]) PVC[0,0,1,mj^2,0,mi^2,mF,mV,mV]-(-2+\[ScriptD]) PVC[0,0,2,mj^2,0,mi^2,mF,mV,mV]+PVC[0,1,0,mj^2,0,mi^2,mF,mV,mV]+2 PVC[0,1,1,mj^2,0,mi^2,mF,mV,mV]-\[ScriptD] PVC[0,1,1,mj^2,0,mi^2,mF,mV,mV]) VFinleft[] VFoutleft[]+mF ((-4+\[ScriptD]) PVC[0,0,0,mj^2,0,mi^2,mF,mV,mV]+(-1+\[ScriptD]) (PVC[0,0,1,mj^2,0,mi^2,mF,mV,mV]+PVC[0,1,0,mj^2,0,mi^2,mF,mV,mV])) VFinleft[] VFoutright[]+mj (PVC[0,0,1,mj^2,0,mi^2,mF,mV,mV]-(-4+\[ScriptD]) PVC[0,1,0,mj^2,0,mi^2,mF,mV,mV]-(-2+\[ScriptD]) (PVC[0,1,1,mj^2,0,mi^2,mF,mV,mV]+PVC[0,2,0,mj^2,0,mi^2,mF,mV,mV])) VFinright[] VFoutright[])]*)
(*]*)
(*]*)
(**)
(*VVFA2R[mi_,mj_,mF_,mV_,VFinleft_,VFoutleft_,VFinright_,VFoutright_]:=Module[{r},*)
(*r=Power[mF/mV,2];*)
(*Return[3.*mF/mj*VFinright[]*VFoutleft[]*OneLoopFunctionK[r]*)
(*+mi/mj*VFinright[]*VFoutright[]*OneLoopFunctionJ[r]/6.*)
(*+VFinleft[]*VFoutleft[]*OneLoopFunctionJ[r]/6.]*)
(*]*)
(*VVFA2RPV[mi_,mj_,mF_,mV_,VFinleft_,VFoutleft_,VFinright_,VFoutright_]:=Module[{r,mV2,\[ScriptD]},*)
(*(*Massless emitter (in this case mV\[Equal]0,mi\[Equal]mj\[Equal]mF) will fail*)*)
(*(*Massless mediator (in this case mF\[Equal]0) case can be calculated*)*)
(*mV2=Power[mV,2];*)
(*If[mi==mj&&mi==mV&&mF==0,*)
(*2.*mV2*(VFinleft[]*VFoutleft[]+VFinright[]*VFoutright[])/Power[mi,2],*)
(*Return[2 mV2/mj (mj (PVC[0,0,1,mj^2,0,mi^2,mF,mV,mV]-(-4+\[ScriptD]) PVC[0,1,0,mj^2,0,mi^2,mF,mV,mV]-(-2+\[ScriptD]) (PVC[0,1,1,mj^2,0,mi^2,mF,mV,mV]+PVC[0,2,0,mj^2,0,mi^2,mF,mV,mV])) VFinleft[] VFoutleft[]+mF ((-4+\[ScriptD]) PVC[0,0,0,mj^2,0,mi^2,mF,mV,mV]+(-1+\[ScriptD]) (PVC[0,0,1,mj^2,0,mi^2,mF,mV,mV]+PVC[0,1,0,mj^2,0,mi^2,mF,mV,mV])) VFinright[] VFoutleft[]+mi (-(-4+\[ScriptD]) PVC[0,0,1,mj^2,0,mi^2,mF,mV,mV]-(-2+\[ScriptD]) PVC[0,0,2,mj^2,0,mi^2,mF,mV,mV]+PVC[0,1,0,mj^2,0,mi^2,mF,mV,mV]+2 PVC[0,1,1,mj^2,0,mi^2,mF,mV,mV]-\[ScriptD] PVC[0,1,1,mj^2,0,mi^2,mF,mV,mV]) VFinright[] VFoutright[])]*)
(*]*)
(*]*)
(**)
(*(*FFV Diagram*)*)
(**)
(*FFVA2L[mi_,mj_,mF_,mV_,VFinleft_,VFoutleft_,VFinright_,VFoutright_]:=Module[{r},*)
(*r=Power[mF/mV,2];*)
(*Return[-4.*mF/mj*VFinleft[]*VFoutright[]*OneLoopFunctionC[r]/3.+mi/mj*VFinleft[]*VFoutleft[]*OneLoopFunctionM[r]/3.+VFinright[]*VFoutright[]*OneLoopFunctionM[r]/3.]*)
(*]*)
(*FFVA2LPV[mi_,mj_,mF_,mV_,VFinleft_,VFoutleft_,VFinright_,VFoutright_]:=Module[{r,mV2,\[ScriptD]},*)
(*mV2=Power[mV,2];*)
(*Return[2 mV2/mj (-mi (2 PVC[0,0,0,mj^2,0,mi^2,mV,mF,mF]+\[ScriptD] PVC[0,0,1,mj^2,0,mi^2,mV,mF,mF]-2 PVC[0,0,2,mj^2,0,mi^2,mV,mF,mF]+\[ScriptD] PVC[0,0,2,mj^2,0,mi^2,mV,mF,mF]+2 PVC[0,1,0,mj^2,0,mi^2,mV,mF,mF]-2 PVC[0,1,1,mj^2,0,mi^2,mV,mF,mF]+\[ScriptD] PVC[0,1,1,mj^2,0,mi^2,mV,mF,mF]) VFinleft[] VFoutleft[]+mF (4 PVC[0,0,0,mj^2,0,mi^2,mV,mF,mF]+\[ScriptD] (PVC[0,0,1,mj^2,0,mi^2,mV,mF,mF]+PVC[0,1,0,mj^2,0,mi^2,mV,mF,mF])) VFinleft[] VFoutright[]-mj (2 PVC[0,0,0,mj^2,0,mi^2,mV,mF,mF]+2 PVC[0,0,1,mj^2,0,mi^2,mV,mF,mF]+\[ScriptD] PVC[0,1,0,mj^2,0,mi^2,mV,mF,mF]-2 PVC[0,1,1,mj^2,0,mi^2,mV,mF,mF]+\[ScriptD] PVC[0,1,1,mj^2,0,mi^2,mV,mF,mF]-2 PVC[0,2,0,mj^2,0,mi^2,mV,mF,mF]+\[ScriptD] PVC[0,2,0,mj^2,0,mi^2,mV,mF,mF]) VFinright[] VFoutright[])]*)
(*]*)
(**)
(*FFVA2R[mi_,mj_,mF_,mV_,VFinleft_,VFoutleft_,VFinright_,VFoutright_]:=Module[{r},*)
(*r=Power[mF/mV,2];*)
(*Return[-4.*mF/mj*VFinright[]*VFoutleft[]*OneLoopFunctionC[r]/3.*)
(*+mi/mj*VFinright[]*VFoutright[]*OneLoopFunctionM[r]/3.*)
(*+VFinleft[]*VFoutleft[]*OneLoopFunctionM[r]/3.]*)
(*]*)
(*FFVA2RPV[mi_,mj_,mF_,mV_,VFinleft_,VFoutleft_,VFinright_,VFoutright_]:=Module[{r,mV2,\[ScriptD]},*)
(*mV2=Power[mV,2];*)
(*Return[2 mV2/mj (-mj (2 PVC[0,0,0,mj^2,0,mi^2,mV,mF,mF]+2 PVC[0,0,1,mj^2,0,mi^2,mV,mF,mF]+\[ScriptD] PVC[0,1,0,mj^2,0,mi^2,mV,mF,mF]-2 PVC[0,1,1,mj^2,0,mi^2,mV,mF,mF]+\[ScriptD] PVC[0,1,1,mj^2,0,mi^2,mV,mF,mF]-2 PVC[0,2,0,mj^2,0,mi^2,mV,mF,mF]+\[ScriptD] PVC[0,2,0,mj^2,0,mi^2,mV,mF,mF]) VFinleft[] VFoutleft[]+mF (4 PVC[0,0,0,mj^2,0,mi^2,mV,mF,mF]+\[ScriptD] (PVC[0,0,1,mj^2,0,mi^2,mV,mF,mF]+PVC[0,1,0,mj^2,0,mi^2,mV,mF,mF])) VFinright[] VFoutleft[]-mi (2 PVC[0,0,0,mj^2,0,mi^2,mV,mF,mF]+\[ScriptD] PVC[0,0,1,mj^2,0,mi^2,mV,mF,mF]-2 PVC[0,0,2,mj^2,0,mi^2,mV,mF,mF]+\[ScriptD] PVC[0,0,2,mj^2,0,mi^2,mV,mF,mF]+2 PVC[0,1,0,mj^2,0,mi^2,mV,mF,mF]-2 PVC[0,1,1,mj^2,0,mi^2,mV,mF,mF]+\[ScriptD] PVC[0,1,1,mj^2,0,mi^2,mV,mF,mF]) VFinright[] VFoutright[])]*)
(*]*)
(**)
(*(*VSF Diagram*)*)
(**)
(*VSFA2L[mi_,mj_,mF_,mV_,mG_,VFinleft_,SFoutleft_,VFinright_,SFoutright_]:=Module[{r,s},*)
(*r=Power[mF/mV,2];*)
(*s=Power[mF/mG,2];*)
(*Return[1./mj*VFinleft[]*SFoutleft[]*OneLoopFunctionN[r,s]]*)
(*]*)
(*VSFA2LPV[mi_,mj_,mF_,mV_,mG_,VFinleft_,SFoutleft_,VFinright_,SFoutright_]:=Module[{r,mV2,\[ScriptD]},*)
(*mV2=Power[mV,2];*)
(*If[mi==mj&&mi==mF&&mV==0&&mG==0,*)
(*mV2,*)
(*Return[(2 mV2 PVC[0,1,0,mj^2,0,mi^2,mF,mV,mG] SFoutleft[] VFinleft[])/mj]*)
(*]*)
(*]*)
(**)
(*VSFA2R[mi_,mj_,mF_,mV_,mG_,VFinleft_,SFoutleft_,VFinright_,SFoutright_]:=Module[{r,s},*)
(*r=Power[mF/mV,2];*)
(*s=Power[mF/mG,2];*)
(*Return[1./mj*VFinright[]*SFoutright[]*OneLoopFunctionN[r,s]]*)
(*]*)
(*VSFA2RPV[mi_,mj_,mF_,mV_,mG_,VFinleft_,SFoutleft_,VFinright_,SFoutright_]:=Module[{r,mV2,\[ScriptD]},*)
(*mV2=Power[mV,2];*)
(*If[mi==mj&&mi==mF&&mV==0&&mG==0,*)
(*mV2,*)
(*Return[(2 mV2 PVC[0,1,0,mj^2,0,mi^2,mF,mV,mG] SFoutright[] VFinright[])/mj]*)
(*]*)
(*]*)
(**)
(*(*SVF Diagram*)*)
(**)
(*SVFA2L[mi_,mj_,mF_,mV_,mG_,SFinleft_,VFoutleft_,SFinright_,VFoutright_]:=Module[{r,s},*)
(*r=Power[mF/mV,2];*)
(*s=Power[mF/mG,2];*)
(*Return[1./mj*SFinleft[]*VFoutright[]*OneLoopFunctionN[r,s]]*)
(*]*)
(*SVFA2LPV[mi_,mj_,mF_,mV_,mG_,SFinleft_,VFoutleft_,SFinright_,VFoutright_]:=Module[{r,mV2,\[ScriptD]},*)
(*(*Massless emitter (in this case mV\[Equal]0,mi\[Equal]mj\[Equal]mF) will fail*)*)
(*(*Massless mediator (in this case mF\[Equal]0) case can be calculated*)*)
(*mV2=Power[mV,2];*)
(*If[mi==mj&&mi==mV&&mF==0,*)
(*mV2,*)
(*Return[(2 mV2 PVC[0,0,1,mj^2,0,mi^2,mF,mG,mV] SFinleft[] VFoutright[])/mj]*)
(*]*)
(*]*)
(**)
(*SVFA2R[mi_,mj_,mF_,mV_,mG_,SFinleft_,VFoutleft_,SFinright_,VFoutright_]:=Module[{r,s},*)
(*r=Power[mF/mV,2];*)
(*s=Power[mF/mG,2];*)
(*Return[1./mj*SFinright[]*VFoutleft[]*OneLoopFunctionN[r,s]]*)
(*]*)
(*SVFA2RPV[mi_,mj_,mF_,mV_,mG_,SFinleft_,VFoutleft_,SFinright_,VFoutright_]:=Module[{r,mV2,\[ScriptD]},*)
(*(*Massless emitter (in this case mV\[Equal]0,mi\[Equal]mj\[Equal]mF) will fail*)*)
(*(*Massless mediator (in this case mF\[Equal]0) case can be calculated*)*)
(*mV2=Power[mV,2];*)
(*If[mi==mj&&mi==mV&&mF==0,*)
(*mV2,*)
(*Return[(2 mV^2 PVC[0,0,1,mj^2,0,mi^2,mF,mG,mV] SFinright[] VFoutleft[])/mj]*)
(*]*)
(*]*)
