ParameterDefinitions = {
  {g1, {Description -> "Hypercharge-Coupling"}},
  {g2, {Description -> "Left-Coupling"}},
  {g3, {Description -> "Strong-Coupling"}},
  {M112, {LaTeX -> "m^2_{1}",
    OutputName -> M112,
    Real -> True,
    LesHouches -> {HMIX, 20}}},
  {M222, {LaTeX -> "m^2_{2}",
    OutputName -> M222,
    Real -> True,
    LesHouches -> {HMIX, 21}}},
  {M12, {LaTeX -> "M_{12}^2",
    OutputName -> M12,
    Real -> True,
    LesHouches -> {HMIX, 22}}},
  {Mm, {LaTeX -> "M_{m}",
    OutputName -> Mm,
    LesHouches -> {HMIX, 23}}},
  {Lambda1, {LaTeX -> "Z_{1111}",
    OutputName -> Lambda1,
    Real -> True,
    LesHouches -> {HMIX, 31}}},
  {Lambda2, {LaTeX -> "Z_{2222}",
    OutputName -> Lambda2,
    Real -> True,
    LesHouches -> {HMIX, 32}}},
  {Lambda3, {LaTeX -> "Z_{2211}",
    OutputName -> Lambda3,
    Real -> True,
    LesHouches -> {HMIX, 33}}},
  {Lambda4, {LaTeX -> "Z_{2112}",
    OutputName -> Lambda4,
    Real -> True,
    LesHouches -> {HMIX, 34}}},
  {Lambda5, {LaTeX -> "Z_{2121}",
    OutputName -> Lambda5,
    Real -> True,
    LesHouches -> {HMIX, 35}}},
  {Ye1, {Description -> "Lepton-Yukawa-Coupling",
    OutputName -> Ye1,
    DependenceNum -> None,
    LesHouches -> Ye1,
    LaTeX -> "Y_{E1}"}},
  {Yd1, {Description -> "Down-Yukawa-Coupling",
    OutputName -> Yd1,
    DependenceNum -> None,
    LesHouches -> Yd1,
    LaTeX -> "Y_{D1}"}},
  {Yu1, {Description -> "Up-Yukawa-Coupling",
    OutputName -> Yu1,
    DependenceNum -> None,
    LesHouches -> Yu1,
    LaTeX -> "Y_{U1}"}},
  {Yu2, {Description -> "Up-Yukawa-Coupling-Dub2",
    OutputName -> Yu2,
    LesHouches -> Yu2,
    LaTeX -> "Y_{U2}"}},
  {Yd2, {Description -> "Down-Yukawa-Coupling-Dub2",
    OutputName -> Yd2,
    LesHouches -> Yd2,
    LaTeX -> "U_{D2}"}},
  {Ye2, {Description -> "Lepton-Yukawa-Coupling-Dub2",
    OutputName -> Ye2,
    LesHouches -> Ye2,
    LaTeX -> "Y_{E1}"}},
  {Yn1, {Description -> "N0-Yukawa-Coupling-Dub1",
    OutputName -> Yn1,
    LesHouches -> Yn1,
    LaTeX -> "Y_{N1}"}},
  {Yn2, {Description -> "N0-Yukawa-Coupling-Dub2",
    OutputName -> Yn2,
    LesHouches -> Yn2,
    LaTeX -> "Y_{N2}"}},
  {ThetaW, {Description -> "Weinberg-Angle"}},
  {ZZ, {Description -> "Photon-Z Mixing Matrix"}},
  {ZW, {Description -> "W Mixing Matrix" }},
  {v, {Description -> "EW-VEV",
    DependenceNum -> Sqrt[4 * Mass[VWp]^2 / (g2^2)],
    DependenceSPheno -> None  }},
  {Vu, {Description -> "Left-Up-Mixing-Matrix"}},
  {Vd, {Description -> "Left-Down-Mixing-Matrix"}},
  {Uu, {Description -> "Right-Up-Mixing-Matrix"}},
  {Ud, {Description -> "Right-Down-Mixing-Matrix"}},
  {Ve, {Description -> "Left-Lepton-Mixing-Matrix"}},
  {Ue, {Description -> "Right-Lepton-Mixing-Matrix"}},
  {Un, {Description -> "Neutrino-Mixing-Matrix",
    LaTeX -> "U_{n}",
    Value -> None,
    LesHouches -> Un,
    OutputName -> Un}},
  {\[Beta], {Description -> "Pseudo Scalar mixing angle"  }},
  {\[Alpha], {Description -> "Scalar mixing angle" }},
  {ZH, {Description -> "Scalar-Mixing-Matrix",
    Dependence -> None,
    DependenceNum -> None,
    DependenceOptional -> None,
    Real -> True}},
  {ZHm, {Description -> "Charged-Mixing-Matrix",
    Real -> False,
    OutputName -> ZHm,
    Dependence -> None,
    DependenceOptional -> None,
    DependenceNum -> None}},
  {AlphaS, {Description -> "Alpha Strong"}},
  {e, {Description -> "electric charge"}},
  {Gf, {Description -> "Fermi's constant"}},
  {aEWinv, {Description -> "inverse weak coupling constant at mZ"}},
  {eta, {Real -> True,
    OutputName -> eta,
    LaTeX -> "\\eta",
    LesHouches -> {HMIX, 500} }}
};
