name: static analysis

on:
  push:
    paths:
      - 'configure'
      - 'createmodel'
      - 'install-sarah'
      - 'createaddon'
      - 'config/*.sh'
      - 'utils/*.sh'
      - 'test/test_*.sh'

  pull_request:
    paths:
      - 'configure'
      - 'createmodel'
      - 'install-sarah'
      - 'createaddon'
      - 'config/*.sh'
      - 'utils/*.sh'
      - 'test/test_*.sh'

jobs:
  check-scripts:
    runs-on: ubuntu-latest

    steps:

      - name: Install shellcheck
        run: |
          apt-get update -y
          apt-get install -y shellcheck

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check scripts
        run: |
           echo "We assume, that shell understands 'local' command!"
           shellcheck -e SC3037 -e SC3043 -S warning configure createmodel install-sarah createaddon config/*.sh utils/*.sh test/test_*.sh
